version: '3'

services:
  app:
    image: phanan/koel
    depends_on:
      - koel-db
    # ports:
    #   - 80:80
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=koel-db
      - DB_PORT=5432
      - DB_USERNAME=koel
      - DB_PASSWORD=${KOEL_PASSWORD}
      - DB_DATABASE=koel
    volumes:
      - /storagebox/media/music:/music
      - /storagebox/media/music/covers:/var/www/html/public/img/covers
      - /docker/koel/search_index:/var/www/html/storage/search-indexes

  db:
    image: postgres:13
    volumes:
      - /docker/koel/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=koel
      - POSTGRES_USER=koel
      - POSTGRES_PASSWORD=${KOEL_PASSWORD}

networks:
  npm_net:
    name: npm_net
    external: true

# volumes:
#   db:
#     driver: local
#   music:
#     driver: local
#   covers:
#     driver: local
#   search_index:
#     driver: local
