version: '3'

services:
  koel:
    image: phanan/koel
    # depends_on:
    #   - database
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres-shared
      - DB_PORT=5432
      - DB_USERNAME=koel
      - DB_PASSWORD=${KOEL_PASSWORD}
      - DB_DATABASE=koel-1
      # - APP_KEY=${KOEL_APP_KEY}
      # - APP_URL=https://koel.jwowk.net
      - FORCE_HTTPS=true
    volumes:
      - /mnt/media/music:/music
      - /mnt/media/music/covers:/var/www/html/public/img/covers
      - search_index:/var/www/html/storage/search-indexes
    networks:
      # - koel_default
      - npm_net

  # database:
  #   image: postgres:13
  #   volumes:
  #     - /docker/koel2/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=koel
  #     - POSTGRES_USER=koel
  #     - POSTGRES_PASSWORD=${KOEL_PASSWORD}
  #   networks:
  #     - koel_default

networks:
  npm_net:
    external: true
  # koel_default:
  #   external: true

volumes:
  search_index:
    driver: local